# Generated by Django 5.0 on 2024-01-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityID', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('StateID', models.AutoField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddressID', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Pincode', models.CharField(max_length=6, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.roles'),
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state'),
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.status'),
        ),
    ]
