# Generated by Django 5.0 on 2024-01-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_state_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='Status_name',
            new_name='Status_Name',
        ),
    ]
