# Generated by Django 5.0 on 2024-04-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_status_name_status_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Address',
        ),
        migrations.AddField(
            model_name='address',
            name='Home',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Landmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='Street',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
