# Generated by Django 5.0 on 2024-01-20 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_rename_status_name_status_status_name'),
        ('cafe', '0003_alter_cafe_address_alter_cafe_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_M',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('OfferID', models.AutoField(primary_key=True, serialize=False)),
                ('OfferTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('OfferDescription', models.TextField(blank=True, null=True)),
                ('MinimumAmount', models.IntegerField(blank=True, null=True)),
                ('DiscountPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('StartDate', models.DateTimeField()),
                ('Endtime', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.status')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Details',
            fields=[
                ('CartDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemQuantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menu')),
                ('Cart_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart_m')),
                ('Offer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_M',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField()),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Review', models.TextField()),
                ('Rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Offer_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.offer')),
                ('Status_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.status')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('OrderDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemQuantity', models.IntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menu')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_m')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('ComplaintID', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Description', models.TextField()),
                ('Complaint_Date', models.DateTimeField()),
                ('Status_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.status')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_m')),
            ],
        ),
    ]
