# Generated by Django 5.0 on 2024-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cart_details_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_m',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
