# Generated by Django 5.0 on 2024-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_m_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='Subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
