# Generated by Django 5.0 on 2024-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_details_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='Subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
