# Generated by Django 5.0 on 2024-03-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_m_offer_id_order_details_offer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_details',
            name='Offer_ID',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='Offer_ID',
        ),
        migrations.AddField(
            model_name='cart_m',
            name='Offer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.offer'),
        ),
        migrations.AddField(
            model_name='order_m',
            name='Offer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.offer'),
        ),
    ]
