# Generated by Django 5.0 on 2024-03-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_cart_details_offer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_m',
            name='Offer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.offer'),
        ),
    ]
