# Generated by Django 5.0 on 2024-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_menu_itemprice'),
        ('order', '0011_cart_m_subtotal'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart_details',
            constraint=models.UniqueConstraint(fields=('Cart_ID', 'Item_ID'), name='unique_cart_item'),
        ),
    ]
