# Generated by Django 5.0 on 2024-03-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_cart_details_unique_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='Cart_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart_m'),
        ),
    ]
