# Generated by Django 5.0 on 2024-03-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_cart_details_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='Cart_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart_m'),
            preserve_default=False,
        ),
    ]
