# Generated by Django 5.0 on 2024-03-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_cart_details_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_M',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateField(auto_now_add=True)),
                ('PaymentTime', models.TimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_m')),
            ],
        ),
    ]
