# Generated by Django 5.0 on 2024-03-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_status_name_status_status_name'),
        ('order', '0016_payment_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_m',
            name='Rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='order_m',
            name='Review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_m',
            name='Status_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.status'),
        ),
    ]
