# Generated by Django 5.0 on 2024-04-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_m_rating_alter_order_m_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_m',
            name='OrderID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.order_m'),
        ),
    ]
