# Generated by Django 5.0 on 2024-01-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_rename_status_name_status_status_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('CafeID', models.AutoField(primary_key=True, serialize=False)),
                ('CafeName', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=30)),
                ('mobile_no', models.CharField(max_length=12)),
                ('Delivery', models.BooleanField(default=False)),
                ('Take_away', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50, null=True)),
                ('verification_documents', models.FileField(blank=True, null=True, upload_to='verification_documents/')),
                ('LogoImage', models.ImageField(blank=True, null=True, upload_to='cafe_logoimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address')),
                ('cafe_managerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.status')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=30)),
                ('ItemDescription', models.TextField(blank=True)),
                ('ItemSize', models.CharField(blank=True, max_length=6, null=True)),
                ('ItemWieght', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.status')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SubCategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('SubCategoryName', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.category')),
            ],
        ),
    ]
