# Generated by Django 5.0 on 2024-01-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='ItemWieght',
            new_name='ItemWeight',
        ),
    ]
