# Generated by Django 5.0 on 2024-01-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_status_name_status_status_name'),
        ('cafe', '0002_rename_itemwieght_menu_itemweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.status'),
        ),
    ]
