# Generated by Django 5.0 on 2024-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_cafe_address_alter_cafe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ItemPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
