# Generated by Django 5.0 on 2024-03-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_menu_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ItemWeight',
            field=models.CharField(max_length=30),
        ),
    ]
